### ISSUE TITLE
Hash/script name needs to be updated

### ISSUE THREAD

**Issue by MasterSpecter** [wizzomafizzo/MiSTer_GamesMenu#10]
Hey so, I forgot to update the hash for the script when I updated it. Now it's getting deleted when I run the update-all script. My bad. Could you handle that? I also noticed that, when I enabled your mister extensions in the new update all script, it looked like it was trying to download the game menu script as the old name (`games_menu.sh`). Not sure if that's because of the hash mismatch, but its a possible bug.

**Comment by wizzomafizzo** [comment]
Oh yeah don't worry that's my fault. I should have updated it. I think it's fixed now

**Comment by MasterSpecter** [comment]
I'm not sure if it's quite fixed yet. I get this from update-all now.
![2022-10-24 20_47_50-Window](https://user-images.githubusercontent.com/14915116/197678039-fcb57085-506d-4ef1-b952-6b117d80c437.png)

**Comment by wizzomafizzo** [comment]
Oh yeah for the mrext/all repo I actually include the favorites, bgm and gamesmenu scripts as a convenience. So there will be a conflict. You can remove the games_menu repo in downloader.ini if you already have mrext/all in there. I will update the version in mrext/all now so it has your fix

**Comment by wizzomafizzo** [comment]
Ok sorted. Just give it 5 minutes in case github is caching it

**Comment by MasterSpecter** [comment]
Sweet, thanks. I was wondering if having that entry still in there would cause issues.
