### ISSUE TITLE
Certain Characters in names.txt break the script

### ISSUE THREAD

**Issue by Jayde6** [wizzomafizzo/MiSTer_GamesMenu#3]
Thanks for this amazing script, I couldn't get it to work at first but realized it was my use of an asterisk before the system names I want to bump up to the top of the list in names.txt that was doing it. Temporarily renaming names.txt allowed your script to work.

**Comment by wizzomafizzo** [comment]
Hi. Could you upload a copy of your names.txt file for me to test? I should be able to get it working or at least work around it. Thanks

**Comment by Jayde6** [comment]
Sure thing! 
[names.txt](https://github.com/wizzomafizzo/MiSTer_GamesMenu/files/8597864/names.txt)

**Comment by wizzomafizzo** [comment]
Update is in now to fix this. I can't technically "fix" it because * is an illegal character in a filename but I've replaced those with spaces. So you should get the same effect with no errors. Thanks again

**Comment by Jayde6** [comment]
> Update is in now to fix this. I can't technically "fix" it because * is an illegal character in a filename but I've replaced those with spaces. So you should get the same effect with no errors. Thanks again

Ah, of course. I didn't even think about it creating folders from the list names. Thanks for the update.
